# Generated by Django 2.1.4 on 2019-01-01 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('image_portrait', models.ImageField(null=True, upload_to='show/')),
                ('image_landscape', models.ImageField(null=True, upload_to='show/')),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
