# Generated by Django 2.1.4 on 2019-01-01 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
