# Generated by Django 2.1.4 on 2019-03-07 13:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0003_show_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='tmdb_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
